### ISSUE TITLE
Error: File extension "svg" is already occupied by require-hacker

### ISSUE THREAD

**Issue by wsfuller** [catamphetamine/require-hacker#7]
For clarity, this is my first attempt at Unit Testing on my first React/Redux project. So trying to figure out the entire ecosystem and log my errors/resolutions. Right now unable to `--watch` unit tests while require-hacker is setup. If I run my tests a single time everything works as expected. The error arises when using the `--watch` flag and saving tests.

*package.json*

    "scripts": {
      "machine": "NODE_ENV=machine webpack-dev-server --progress",
      "test": "mocha --compilers js:babel-core/register --compilers jsx:babel-register --require ./test/test_helper.js --require ./test/test_ignore.js --recursive ./test",
      "test:watch": "npm run test -- --watch"
    },
    devDependencies:{
      "babel": "~6.23.0",
      "babel-core": "~6.23.1",
      ...other babel dependencies...
      "chai": "~3.5.0",
      "chai-jquery": "~2.0.0",
      "jquery": "~2.2.1",
      "jsdom": "~9.11.0",
      "mocha": "~2.4.5",
      "require-hacker": "^3.0.0",
      "webpack": "~2.2.1",
      "webpack-dev-server": "~2.4.1"
    }

*test_ignore.js*

    import requireHacker from 'require-hacker';
    
    requireHacker.hook('svg', () => 'module.exports = ""')

[test_helper.js](https://github.com/StephenGrider/ReduxSimpleStarter/blob/master/test/test_helper.js)

*MyComponent.jsx*

    import React, {Component} from 'react';
    import logo from './path/to/logo/logo.svg';
    
    export default class MyComponent extends Component{
      ...
      render(){
        return(<div className="MyComponent"><img className="logo" src={logo} /></div>)
      }
    }

*MyComponent_test.js*

    import React from 'react';
    import { renderComponent, expect } from '../test_helper';

    import MyComponent from '../path/to/MyComponent.jsx';

    describe('MyComponent', () => {
      // some unit tests
    }

The reason I'm using this plugin is I was getting SyntaxError when importing the SVG image. So I followed this [guide](https://diessi.ca/blog/how-to-exclude-css-images-anything-from-unit-tests/) which brought me to this module. Using this module I was able to run `yarn run test` and have my tests run and work as expected. However continually running tests with `yarn run test:watch` on initial load it is fine but when I save changes to a test file the error `Error: File extension "svg" is already occupied by require-hacker` is present. 

Is there some additional setup I'm missing here?

*full log*

    Error: File extension "svg" is already occupied by require-hacker
    at Object.extension (/node_modules/require-hacker/babel-transpiled-modules/require hacker.js:382:10)
    at Object.hook (/node_modules/require-hacker/babel-transpiled-modules/require hacker.js:230:12)
    at Object.<anonymous> (/test/test_ignore.js:10:15)
    at Module._compile (module.js:571:32)
    at loader (/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /node_modules/mocha/lib/mocha.js:219:27
    at Array.forEach (native)
    at Mocha.loadFiles (/node_modules/mocha/lib/mocha.js:216:14)
    at Mocha.run (/node_modules/mocha/lib/mocha.js:468:10)
    at loadAndRun (/node_modules/mocha/bin/_mocha:359:22)
    at rerun (/node_modules/mocha/bin/_mocha:386:5)
    at /node_modules/mocha/bin/_mocha:394:7
    at StatWatcher.<anonymous> (/node_modules/mocha/lib/utils.js:173:9)
    at emitTwo (events.js:106:13)
    at StatWatcher.emit (events.js:194:7)
    at StatWatcher._handle.onchange (fs.js:1459:10)

**Comment by catamphetamine** [comment]
Well, seems that `requireHacker.hook()` is being called the second time and this triggers the error.
Dunno.
You're on your own in this case.

**Comment by wsfuller** [comment]
Ok, see the issue thanks for pointing that out. Looks like the error is in the `"scripts":{"test":"--recursive ./test"}` that was calling it again throwing the error. Just nested the test files into `src` to match my `/app/src` structure and updated `--recrusive ./test/src` and that seems to have fixed the issue.
